### ISSUE TITLE
Installing bode-jpeg-turbo windows server 2012 r2

### ISSUE THREAD

**Issue by kkoci** [sorccu/node-jpeg-turbo#3]
Hi sorccu

I'm building the stf project on windows server 2012, I think I'm on a good point on this.

Anyways, the only problem I'm still facing is with the node-jpeg-turbo module

I'm installing it via npm install -g stf --msvs_version=2013

Everything installs but this module, it throws me this error:

yasm: Error FATAL: Unable to open include file 'jsimdcfg.inc'

I'm using yasm version 1.3.0 for windows x64

It is already on C:\windows\yasm

Changed yasm name from yasm-1.3.0-x64 to simply yasm.exe, added to win PATH.

I can run it from cmd terminal, only when I'm installing node-jpeg-turbo module it throws that error

Any ideas?

Thank You in advance!

**Comment by sorccu** [comment]
Great to hear that you're working on it.

I think you'll have to add one of these gyp conditional sections for Windows and set the correct values: https://github.com/sorccu/node-jpeg-turbo/blob/69295e8b5f2f87c006e4cfd6731d0b8caf34b5fa/deps/libjpeg-turbo.gyp#L248

I am not entirely sure how to configure it for Windows, but please try to find a way and let me know how it goes :) I would be very happy to accept a pull request.

**Comment by kkoci** [comment]
Thank You Very Much

I'm going to try it, btw I'm installing everything from npm tho, if I try your patch, then I guess I'll have to clone the repo and make the changes, then install from there, right? 

Yeah I'm confident I'll find a way :)

**Comment by taotl** [comment]
hi  kkoci 
I have encountered the same problem with you, you have a successful resolution of the problem? Can you tell me your solution?
thank you very much！

**Comment by Payne-jin** [comment]
@kkoci 
hi kkoci 
I have encountered the same problem with you, you have a successful resolution of the problem? Can you tell me your solution?
thank you very much！
