### ISSUE TITLE
Bindings fails on ubuntu with electron 1.1.0

### ISSUE THREAD

**Issue by ignjat** [sorccu/node-jpeg-turbo#4]
Electron 1.1.0 brings node.js 6.1 and one can't use jpeg-turbo with it.

**Comment by sorccu** [comment]
It works fine but there are no prebuilt binaries yet.

**Comment by ignjat** [comment]
Thanks for the quick response, when could we expect a prebuilt binary?

**Comment by ignjat** [comment]
Any update on prebuilt binaries?
Recursive cloning fails with:
fatal: reference is not a tree: 0d293537728f211888b04bed6ee19f71e0bda504
Unable to checkout '0d293537728f211888b04bed6ee19f71e0bda504' in submodule path 'deps/libjpeg-turbo'

**Comment by sorccu** [comment]
That error was caused by libjpeg-turbo doing a force push. Anyway I'll be releasing a new version with prebuilts soon, feel free to open a new issue if it's still an issue after that.
