### ISSUE TITLE
Build fail in node 6.2.2/6.3

### ISSUE THREAD

**Issue by Ivan-Feofanov** [sorccu/node-jpeg-turbo#7]
When i try to install this package node throw error:

npm ERR! enoent ENOENT: no such file or directory, chmod '/vagrant/backend/s3dicom/node_modules/jpeg-turbo/node_modules/node-pre-gyp/node_modules/mkdirp/bin/cmd.js'

In builds fine on node v0.12, but i use v6.2.2 in my project.

Any ideas?

**Comment by sorccu** [comment]
It builds fine on my machine and our docker images using 6.3. Perhaps try `rm -rf node_modules` and do a fresh `npm install`? You have to do that if you switch between major versions of node.

**Comment by Ivan-Feofanov** [comment]
It didn't help

**Comment by sorccu** [comment]
Not sure what the original issue was (perhaps a Vagrant-only thing), but it may have been fixed in the master branch by moving away from node-pre-gyp. Should be OK in the next release.
