### ISSUE TITLE
Can't install this module with Node.js version 6.

### ISSUE THREAD

**Issue by DonnaWuDongxia** [sorccu/node-jpeg-turbo#9]
---- Description ---------
This module can be install successfully with Node.js Version 4.8.4, but can not be installed under Node.js Version 6.

----- Node & NPM version ----
panda@xxx:~/rs/node-realsense-1/samples/or_tutorial_2_web$ node --version
v6.11.3
panda@xxx:~/rs/node-realsense-1/samples/or_tutorial_2_web$ npm --version
3.10.10
panda@xxx:~/rs/node-realsense-1/samples/or_tutorial_2_web$ uname -a 
Linux xxx: 4.8.0-36-generic #36~16.04.1-Ubuntu SMP Sun Feb 5 09:39:57 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

---------------- The error log ---------
panda@latte-panda:~$ npm install jpeg-turbo

> jpeg-turbo@0.4.0 install /home/panda/node_modules/jpeg-turbo
> node-pre-gyp install --fallback-to-build

make: Entering directory '/home/panda/node_modules/jpeg-turbo/build'
  RULE deps_libjpeg_turbo_gyp_jpeg_turbo_target_assemble_0 Release/obj/gen/jfdctflt-sse-64.o
/bin/sh: 1: yasm: not found
deps/jpeg-turbo.target.mk:10: recipe for target 'Release/obj/gen/jfdctflt-sse-64.o' failed
make: *** [Release/obj/gen/jfdctflt-sse-64.o] Error 127
make: Leaving directory '/home/panda/node_modules/jpeg-turbo/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/panda/.nvm/versions/node/v6.11.3/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
gyp ERR! System Linux 4.8.0-36-generic
gyp ERR! command "/home/panda/.nvm/versions/node/v6.11.3/bin/node" "/home/panda/.nvm/versions/node/v6.11.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/panda/node_modules/jpeg-turbo/lib/binding/node-v48-linux-x64/jpegturbo.node" "--module_name=jpegturbo" "--module_path=/home/panda/node_modules/jpeg-turbo/lib/binding/node-v48-linux-x64"
gyp ERR! cwd /home/panda/node_modules/jpeg-turbo
gyp ERR! node -v v6.11.3
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/home/panda/.nvm/versions/node/v6.11.3/bin/node /home/panda/.nvm/versions/node/v6.11.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/panda/node_modules/jpeg-turbo/lib/binding/node-v48-linux-x64/jpegturbo.node --module_name=jpegturbo --module_path=/home/panda/node_modules/jpeg-turbo/lib/binding/node-v48-linux-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/panda/node_modules/jpeg-turbo/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:920:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
node-pre-gyp ERR! System Linux 4.8.0-36-generic
node-pre-gyp ERR! command "/home/panda/.nvm/versions/node/v6.11.3/bin/node" "/home/panda/node_modules/jpeg-turbo/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/panda/node_modules/jpeg-turbo
node-pre-gyp ERR! node -v v6.11.3
node-pre-gyp ERR! node-pre-gyp -v v0.6.19
node-pre-gyp ERR! not ok 
Failed to execute '/home/panda/.nvm/versions/node/v6.11.3/bin/node /home/panda/.nvm/versions/node/v6.11.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/panda/node_modules/jpeg-turbo/lib/binding/node-v48-linux-x64/jpegturbo.node --module_name=jpegturbo --module_path=/home/panda/node_modules/jpeg-turbo/lib/binding/node-v48-linux-x64' (1)
npm WARN enoent ENOENT: no such file or directory, open '/home/panda/package.json'
npm WARN panda No description
npm WARN panda No repository field.
npm WARN panda No README data
npm WARN panda No license field.
npm ERR! Linux 4.8.0-36-generic
npm ERR! argv "/home/panda/.nvm/versions/node/v6.11.3/bin/node" "/home/panda/.nvm/versions/node/v6.11.3/bin/npm" "install" "jpeg-turbo"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! jpeg-turbo@0.4.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the jpeg-turbo@0.4.0 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the jpeg-turbo package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs jpeg-turbo
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls jpeg-turbo
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/panda/npm-debug.log
panda@latte-panda:~$

**Comment by sorccu** [comment]
It should work just fine. Your error log doesn’t say what the actual error is. Perhaps you left something out?

**Comment by DonnaWuDongxia** [comment]
@sorccu but in the same ENV, it works when I switched to node V4.8.

**Comment by sorccu** [comment]
You need to provide more details or I can’t do anything. The error log you posted doesn’t say anything useful.

**Comment by DonnaWuDongxia** [comment]
@sorccu the error log has been updated.

**Comment by sorccu** [comment]
It says what your error is... “yasm: not found”. Fix that and try again.

**Comment by DonnaWuDongxia** [comment]
@sorccu it's the cause, thank you very much!

**Comment by mrjeanjoseph** [comment]
Hi,
I am having the same issue with turbo. I followed the turbo documentation at [Turbo Doc](https://docs.turbo360.co/), and git bash returns 
$ turbo version
bash: turbo: command not found
